name: lightnovel
description: "A light novel reading app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State management
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

  # Navigation
  go_router: ^13.2.0

  # Network
  dio: ^5.4.1
  web_socket_channel: ^2.4.0
  
  # UI
  flex_color_scheme: ^7.3.1
  
  # Utils
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  uuid: ^4.3.3
  intl: ^0.19.0
  url_launcher: ^6.1.14
  shared_preferences: ^2.5.3
  flutter_colorpicker: ^1.1.0
  battery_plus: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.otf
        - asset: assets/fonts/NotoSansSC-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansSC-Bold.otf
          weight: 700

