basePath: /api/v1
definitions:
  models.Bookmark:
    properties:
      chapterNumber:
        type: integer
      createdAt:
        type: string
      deviceId:
        type: string
      id:
        type: string
      note:
        type: string
      novelId:
        type: string
      position:
        type: integer
      updatedAt:
        type: string
      volumeNumber:
        type: integer
    type: object
  models.Chapter:
    properties:
      chapterNumber:
        type: integer
      content:
        type: string
      createdAt:
        type: string
      hasImages:
        type: boolean
      id:
        type: string
      imageCount:
        type: integer
      imagePath:
        type: string
      novelId:
        type: string
      title:
        type: string
      updatedAt:
        type: string
      volumeNumber:
        type: integer
    type: object
  models.ChapterInfo:
    properties:
      chapterNumber:
        type: integer
      createdAt:
        type: string
      id:
        type: string
      novelId:
        type: string
      title:
        type: string
      updatedAt:
        type: string
      volumeNumber:
        type: integer
    type: object
  models.CurrentProgress:
    properties:
      chapterNumber:
        type: integer
      lastReadAt:
        type: string
      position:
        type: integer
      volumeNumber:
        type: integer
    type: object
  models.Novel:
    properties:
      author:
        type: string
      cover:
        type: string
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      readCount:
        description: 阅读量
        type: integer
      status:
        description: 连载中、已完结
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      updatedAt:
        type: string
      volumeCount:
        type: integer
    type: object
  models.ReadingProgress:
    properties:
      createdAt:
        type: string
      currentProgress:
        $ref: '#/definitions/models.CurrentProgress'
      deviceId:
        type: string
      id:
        type: string
      novelId:
        type: string
      updatedAt:
        type: string
    type: object
  models.Volume:
    properties:
      chapterCount:
        type: integer
      createdAt:
        type: string
      id:
        type: string
      novelId:
        type: string
      updatedAt:
        type: string
      volumeNumber:
        type: integer
    type: object
  response.PageResponse:
    properties:
      data: {}
      hasNext:
        type: boolean
      page:
        type: integer
      size:
        type: integer
      total:
        type: integer
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  v1.UpdateProgressRequest:
    properties:
      chapterNumber:
        type: integer
      novelId:
        type: string
      position:
        type: integer
      volumeNumber:
        type: integer
    required:
    - chapterNumber
    - novelId
    - volumeNumber
    type: object
info:
  contact: {}
  description: 轻小说阅读API服务
  title: Light Novel API
  version: "1.0"
paths:
  /novels:
    get:
      consumes:
      - application/json
      description: 获取小说列表，支持分页
      parameters:
      - default: 1
        description: 页码
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 10
        description: 每页数量
        in: query
        maximum: 50
        minimum: 1
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.PageResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Novel'
                  type: array
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取所有小说
      tags:
      - novels
  /novels/{id}:
    get:
      consumes:
      - application/json
      description: 根据ID获取小说详情
      parameters:
      - description: 小说ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.Novel'
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: 小说不存在
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取小说详情
      tags:
      - novels
  /novels/{id}/volumes:
    get:
      consumes:
      - application/json
      description: 获取指定小说的所有卷列表
      parameters:
      - description: 小说ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Volume'
                  type: array
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: 小说不存在
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取小说卷列表
      tags:
      - novels
  /novels/{id}/volumes/{volume}/chapters:
    get:
      consumes:
      - application/json
      description: 获取指定卷的所有章节基本信息（不包含内容）
      parameters:
      - description: 小说ID
        in: path
        name: id
        required: true
        type: string
      - description: 卷号
        in: path
        name: volume
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ChapterInfo'
            type: array
      summary: 获取卷的所有章节
      tags:
      - novels
  /novels/{id}/volumes/{volume}/chapters/{chapter}:
    get:
      consumes:
      - application/json
      description: 获取指定章节的详细内容
      parameters:
      - description: 小说ID
        in: path
        name: id
        required: true
        type: string
      - description: 卷号
        in: path
        name: volume
        required: true
        type: integer
      - description: 章节号
        in: path
        name: chapter
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Chapter'
      summary: 获取章节内容
      tags:
      - novels
  /novels/latest:
    get:
      consumes:
      - application/json
      description: 获取最新更新的小说列表
      parameters:
      - default: 10
        description: 限制数量
        in: query
        maximum: 100
        minimum: 1
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Novel'
                  type: array
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取最新小说
      tags:
      - novels
  /novels/popular:
    get:
      consumes:
      - application/json
      description: 获取阅读量最高的小说列表
      parameters:
      - default: 10
        description: 限制数量
        in: query
        maximum: 100
        minimum: 1
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Novel'
                  type: array
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取热门小说
      tags:
      - novels
  /novels/search:
    get:
      consumes:
      - application/json
      description: 根据关键词搜索小说
      parameters:
      - description: 搜索关键词
        in: query
        name: keyword
        required: true
        type: string
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 搜索小说
      tags:
      - novels
  /user/bookmarks:
    get:
      consumes:
      - application/json
      description: 获取用户的所有书签
      parameters:
      - description: 设备ID，如果未提供则使用客户端IP
        in: header
        name: X-Device-ID
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Bookmark'
                  type: array
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取用户书签
      tags:
      - user
  /user/history:
    get:
      consumes:
      - application/json
      description: 获取用户的阅读历史记录
      parameters:
      - description: 设备ID，如果未提供则使用客户端IP
        in: header
        name: X-Device-ID
        type: string
      - default: 10
        description: 限制数量
        in: query
        maximum: 100
        minimum: 1
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.ReadingProgress'
                  type: array
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取阅读历史
      tags:
      - user
  /user/progress:
    patch:
      consumes:
      - application/json
      description: 更新用户的小说阅读进度
      parameters:
      - description: 设备ID，如果未提供则使用客户端IP
        in: header
        name: X-Device-ID
        type: string
      - description: 阅读进度信息
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/v1.UpdateProgressRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: 小说不存在
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: 更新阅读进度
      tags:
      - user
swagger: "2.0"
