server:
  port: "8080"
  readTimeout: 10s
  writeTimeout: 10s

database:
  uri: "mongodb://localhost:27017"
  database: "lightnovel"
  poolSize: 100

redis:
  host: "localhost"
  port: "6379"
  password: "whx051021"
  db: 0
  poolSize: 100

cache:
  novelList: 15m
  novelDetail: 30m
  volumeList: 20m
  chapterList: 20m
  chapterDetail: 1h
  searchResult: 10m
  latestNovels: 5m
  popularNovels: 30m

rate:
  limit: 100
  burst: 200
  window: 1 