# ****************************************************************************
#
# @file       config.yaml
# @brief      后端的配置文件
#
# @author     KBchulan
# @date       2025/03/21
# @history
# ****************************************************************************

server:
  port: "8080"
  readTimeout: 10s
  writeTimeout: 10s

database:
  uri: "mongodb://localhost:27017"
  database: "lightnovel"
  poolSize: 300

redis:
  host: "localhost"
  port: "6379"
  password: "whx051021"
  db: 0
  poolSize: 300

cache:
  novel: 24h
  volume: 24h
  chapter: 24h
  search: 1h
  bookmark: 1h
  favorite: 1h
  readHistory: 1h
  readProgress: 1h
  user: 24h
  comment: 30m

rate:
  limit: 200
  burst: 1000
  window: 1