server:
  port: "8080"
  readTimeout: 10s
  writeTimeout: 10s

database:
  uri: "mongodb://localhost:27017"
  database: "lightnovel"
  poolSize: 200

redis:
  host: "localhost"
  port: "6379"
  password: "whx051021"
  db: 0
  poolSize: 200

cache:
  novelList: 30m
  novelDetail: 1h
  volumeList: 40m
  chapterList: 40m
  chapterDetail: 2h
  searchResult: 20m
  latestNovels: 10m
  popularNovels: 1h

rate:
  limit: 200
  burst: 400
  window: 1 